baseURL = "https://judahgnewman.netlify.com/"
languageCode = "en-us"
title = "Welcome"
theme = "minimal_update"



[params]
    author = "Judah Newman"
    description = '''A place for me (Judah Newman) to chronicle my journey'''
    githubUsername = "jgnewman96"
    accent = "darkolivegreen"
    showBorder = true
    backgroundColor = "azure"
    font = "Ubuntu" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "python"]
    googleAnalytics = "UA-169213754-1"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/writing/"
    name = "Writing"
    weight = 3

[[menu.main]]
    url = "/reading/"
    name = "Reading"
    weight = 4

[[menu.main]]
    url = "/research/"
    name = "Research"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:judah.newman@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jgnewman96/"
    name = "github"
    weight = 2


[[menu.icon]]
    url = "https://www.linkedin.com/in/jgnewman96/"
    name = "linkedin"
    weight = 4




